name: build and deploy

on: [push]

jobs:
  apps: 
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        run: sudo docker login -u marcelcernica -p ${{ DOCKERHUB_PASSWORD }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List 
        run: ls -alh
      - name: Build nginx image 
        run: cd apps/nginx && sudo docker build -t marcelcernica/new-nginx:latest .
      - name: Push nginx image
        run: sudo docker login -u marcelcernica && sudo docker push marcelcernica/new-nginx:latest
      - name: Build mysql image 
        run: cd apps/mysql && sudo docker build -t marcelcernica/new-mysql:latest .
      - name: Push mysql image
        run: sudo docker push marcelcernica/new-mysql:latest
      - name: Build wordpress image 
        run: cd apps/wordpress && sudo docker build -t marcelcernica/new-wordpress:latest .
      - name: Push wordpress image
        run: sudo docker push marcelcernica/new-wordpress:latest
      - name: Build containers and networks
        run: sudo docker-compose up -d

        