name: Deploy

on: [push]

jobs:
  apps: 
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List 
        run: ls -alh
      - name: Build nginx
        run: |
          cd apps/nginx && sudo docker build -t marcelcernica/new-nginx:test .
          sudo docker push marcel/cernica/new-nginx:test
      - name: Build mysql 
        run: |
          cd apps/mysql && sudo docker build -t marcelcernica/new-mysql:test .
          sudo docker push marcelcernica/new-mysql:test
      - name: Build wordpress
        run: |
          cd apps/wordpress && sudo docker build -t marcelcernica/new-wordpress:test .
          sudo docker push marcelcernica/new-wordpress:test
        