name: build and deploy

on: [push]

jobs:
  apps: 
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login 
        run: sudo docker login -u marcelcernica -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build nginx image 
        run: cd apps/nginx && sudo docker build -t marcelcernica/new-nginx:0.1 .
      - name: Push nginx image
        run: sudo docker push marcelcernica/new-nginx:0.1
      - name: Build mysql image 
        run: cd apps/mysql && sudo docker build -t marcelcernica/new-mysql:0.1 .
      - name: Push mysql image
        run: sudo docker push marcelcernica/new-mysql:0.1
      - name: Build wordpress image 
        run: cd apps/wordpress && sudo docker build -t marcelcernica/new-wordpress:0.1 .
      - name: Push wordpress image
        run: sudo docker push marcelcernica/new-wordpress:0.1
      - name: Build containers and networks
        run: sudo docker-compose up -d

        